version: "3.9"
services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: realestate-etl
      PGUSER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "${PWD}:/app/user/realestate-etl"
